Sitegeist:
  Monocle:
    ComponentExport:

      #
      # The list of available export presets
      #
      presets:

        #
        # Plain fusion ast export without further processing
        #
        default:
          description: "Export the unmodified fusion ast"
          filters: []

        #
        # Export all styleguide-items plus their dependencies and create render pathes
        #
        styleguideItems:
          description: "Export all styleguide items and create render pathes"

          #
          # Fusion ast filter-chain
          #
          # Each filter has to implement \Sitegeist\Monocle\ComponentExport\Service\FusionAstFilter\FusionAstFilterInterface
          # and can be configured with optional arguments.
          #
          # The order of the filters can be controlled via the optional `position` property
          #
          filters:
            removeStyleguidePropsFilter:
              position: 'after filterPrototypes'
              class: \Sitegeist\Monocle\ComponentExport\Service\FusionAstFilter\RemoveStyleguideProps

            filterPrototypes:
              position: 'start'
              class: \Sitegeist\Monocle\ComponentExport\Service\FusionAstFilter\FilterPrototypes

              #
              # Definition of the Prototypes that shall be included in the export
              # All conditions that are given as arguments must be satisfied to include a prototype
              #
              arguments: &styleguidePprototypeListDefinition
                # Limit prototypes by fusion path that has to exist
                path: '__meta.styleguide'

                # Limit prototypes via pattern applied to the vendor name
                # vendor: 'Vendor.*'

                # Limit prototypes via pattern applied to the fusion name
                # name: 'Component.*'

            createRenderPathes:
              position: 'end'
              class: \Sitegeist\Monocle\ComponentExport\Service\FusionAstFilter\CreateRenderPathes
              arguments: *styleguidePprototypeListDefinition

